const exchanges = ["CCCAGG","TC38", "BTCC", "BTER", "BIT2C", "BITFINEX", "BITSTAMP", "BITTREX", "CEXIO", "COINBASE", "COINFLOOR", "COINSE", "CRYPTOPIA", "GATECOIN", "GEMINI", "HITBTC", "HUOBI", "ITBIT", "KRAKEN", "LAKEBTC", "LOCALBITCOINS", "MONETAGO", "OKCOIN", "POLONIEX", "YACUNA", "YUNBI", "YOBIT", "KORBIT", "BITBAY", "BTCMARKETS", "QUADRIGACX", "COINCHECK", "BITSQUARE", "VAULTORO", "MERCADOBITCOIN", "UNOCOIN", "BITSO", "BTCXINDIA", "PAYMIUM", "THEROCKTRADING", "BITFLYER", "QUOINE", "LUNO", "ETHERDELTA", "LIQUI", "BITFLYERFX", "BITMARKET", "LIVECOIN", "COINONE", "TIDEX", "BLEUTRADE", "ETHEXINDIA"];
export default exchanges;


